---
- name: be sure ntp is installed
  apt: name=ntp state=installed
  tags: ntp

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify:
    - restart ntp

- name: be sure ntp is running and enabled
  service: name=ntp state=running enabled=yes
  tags: ntp

- name: be sure utility packages are installed
  apt: name={{ item }} state=installed
  with_items:
    - tree
    - zsh
